# Generated by Django 5.1.2 on 2024-10-27 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view_sensitive_data', 'Can view sensitive book data')]},
        ),
    ]
